lineButton.addEventListener("click", buttonLineHandler);
squareButton.addEventListener("click", buttonSquareHandler);
rectangleButton.addEventListener("click", buttonRectangleHandler);
quadrilateralButton.addEventListener("click", buttonQuadrilateralHandler);
polygonButton.addEventListener("click", buttonPolygonHandler);
recolorSelection.addEventListener("input", changeCurrObjColor);
clearButton.addEventListener("click", buttonClearHandler);
downloadButton.addEventListener("click", buttonDownloadHandler);
fileInput.value = "";
fileInput.addEventListener("change", buttonUploadHandler, false);
